Updates

diff --git a/example/pipeline/_common b/example/pipeline/_common
--- a/example/pipeline/_common
+++ b/example/pipeline/_common
@@ -16,6 +16,56 @@ die () {
     exit 1
 }
 
+if [ ! -n "$JAVACMD" ] ; then
+    if [ -n "$JAVA_HOME" ] ; then
+        if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+            # IBM's JDK on AIX uses strange locations for the executables
+            JAVACMD="$JAVA_HOME/jre/sh/java"
+        else
+            JAVACMD="$JAVA_HOME/bin/java"
+        fi
+        if [ ! -x "$JAVACMD" ] ; then
+            die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
+    Please set the JAVA_HOME variable in your environment to match the
+    location of your Java installation."
+        fi
+    else
+        JAVA_VERSION='10.0.2'
+        JDK_DIR="/tmp/~jdk-${JAVA_VERSION}"
+        
+        if [ ! -d "${JDK_DIR}" ] ; then
+            #echo "cygwin:${cygwin}, darwin:${darwin}, msys:${msys}, nonstop:${nonstop}"
+            if $darwin; then
+                JDK_DOWNLOAD_URL='https://download.java.net/java/GA/jdk10/10.0.2/19aef61b38124481863b1413dce1855f/13/openjdk-10.0.2_osx-x64_bin.tar.gz'
+            else
+                JDK_DOWNLOAD_URL='https://download.java.net/java/GA/jdk10/10.0.2/19aef61b38124481863b1413dce1855f/13/openjdk-10.0.2_linux-x64_bin.tar.gz'
+            fi
+            JDK_DOWNLOAD_URL_SHA256="${JDK_DOWNLOAD_URL}.sha256"
+            JDK_DOWNLOAD_FILE="${JDK_DIR}.tar.gz"
+            JDK_DOWNLOAD_FILE_SHA256="${JDK_DOWNLOAD_FILE}.sha256"
+
+            curl -sL -o "${JDK_DOWNLOAD_FILE_SHA256}" "${JDK_DOWNLOAD_URL_SHA256}"
+            echo "`cat "${JDK_DOWNLOAD_FILE_SHA256}"`  ${JDK_DOWNLOAD_FILE}" > "${JDK_DOWNLOAD_FILE}.checksum"
+
+            shasum -a 256 -c -s "${JDK_DOWNLOAD_FILE}.checksum" > /dev/null || ( rm -f "${JDK_DOWNLOAD_FILE}"; rm -rf "${JDK_DIR}")
+
+            if [ ! -f "${JDK_DOWNLOAD_FILE}" ] ; then
+                info "Downloading JDK"
+                curl -sL -o "${JDK_DOWNLOAD_FILE}" "${JDK_DOWNLOAD_URL}"
+            fi
+
+            info "Extracting JDK"
+            mkdir -p "${JDK_DIR}"
+            tar -xzf "${JDK_DOWNLOAD_FILE}" -C "${JDK_DIR}"
+        fi
+        JAVACMD="`find "${JDK_DIR}" -type f -name 'java' -perm +111`"
+        #for java 10
+        export JAVA_OPTS="${JAVA_OPTS} --add-modules java.xml.bind --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --show-version"
+    fi
+fi
+
+export JAVACMD
+
 GROOVY_DOWNLOAD_URL='https://dl.bintray.com/groovy/maven/apache-groovy-binary-2.5.2.zip'
 GROOVY_DOWNLOAD_FILE="/tmp/~`basename "$GROOVY_DOWNLOAD_URL"`"
 
@@ -33,9 +83,9 @@ fi
 GROOVYCMD="${GROOVY_DIR}/groovy-2.5.2/bin/groovy"
 
 #echo "JAVACMD=${JAVACMD}"
-export JAVACMD
-#for java 10
-#export JAVA_OPTS='--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED'
+#export JAVACMD
+
+
 
 OCP_PIPELINE_VERSION='0.0.4'
 OCP_PIPELINE_DOWNLOAD_URL="https://dl.bintray.com/cvarjao/maven/ca/bc/gov/devops/cd/pipeline/ocp-pipeline/${OCP_PIPELINE_VERSION}/ocp-pipeline-${OCP_PIPELINE_VERSION}.jar"
